name: photo_label_app
description: 摄影标签管理 - 跨平台版(Android+iOS)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0
  flutter: '>=3.41.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  path: ^1.9.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/labels_config.json
