platform :ios, '15.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'
project 'Runner', {
  'Debug' => :debug,
  'Profile' => :profile,
  'Release' => :release,
}

flutter_root = File.expand_path('../../..', __FILE__)
generated_xcode_build_settings_path = File.expand_path(
  File.join('ios', 'Flutter', 'Generated.xcconfig'), flutter_root
)

unless File.exist?(generated_xcode_build_settings_path)
  generated_xcode_build_settings_path = File.expand_path(
    File.join('ios', 'Flutter', 'Release.xcconfig'), flutter_root
  )
end

unless File.exist?(generated_xcode_build_settings_path)
  raise "Generated.xcconfig must exist. Run `flutter pub get` first."
end

File.foreach(generated_xcode_build_settings_path) do |line|
  matches = line.match(/FLUTTER_ROOT\=(.*)/)
  if matches
    flutter_root = matches[1].strip
    break
  end
end

load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
